lib/react_client.dart

onContextMenu wasn't giving a Dart-wrapped SyntheticMouseEvent.  It appeared to be the only one missing from this list: http://facebook.github.io/react/docs/events.html#mouse-events

Added "onContextMenu" as a SyntheticMouseEvent

---

lib/react.dart
lib/react_client.dart

Addresses #39.
Adds a `SyntheticDataTransfer` class that mirrors the JS `DataTransfer` class detailed here: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer
I currently have the properties on this `dataTransfer` object set as final, but there are scenarios where the user should be able to set the value to have some effect (see above link for more details), but this will require forwarding those updates to the original JsObject.
@hleumas

Add SyntheticDataTransfer for SyntheticMouseEvents

---

lib/react_test_utils.dart
test/react_test_utils_test.dart

While working with the dart react test utils it was discovered that it was necessary to simulate some native events in order to initiate a mouseEnter or mouseLeave event during testing.
In this work, the necessary events events were added in order to create those events within the dart react test utils.
issue originally documented - http://stackoverflow.com/questions/24140773/could-not-simulate-mouseenter-event-using-react-test-utils

Adding mouseOut and mouseOver native events

---

lib/react_test_utils.dart
test/react_test_utils_test.dart

Currently, some of the methods in `react_test_utils.dart` don't work properly, and there are 4 failures and 2 errors in the related tests.
* Pass component type instead of factory into various ReactTestUtils JS functions (factories don't work after the React JS 0.13 upgrade).
* Apply workaround needed for `isCompositeComponent` (see https://github.com/facebook/react/pull/3839)
* Fix test that wasn't passing in a `JsObject` when it should have been.
* Update test util comments and test descriptions.
Run `pub serve`, navigate to http://localhost:8080/react_test_utils_test.html, and verify that all tests are passing.

Fix ReactTestUtils and its tests

---

lib/react_client.dart

In FireFox, Dragging would sometimes leave files and types null instead of a 0 length array.
In IE, Dragging from outside the browser would cause an exception when the property dataTransfer.effectAllowed was accessed.
See #61

Fixing drag n drop in FireFox and outside the browser in IE

---

lib/react.dart
lib/react_client.dart
lib/react_server.dart

This adds support for `React.renderToStaticMarkup` which is useful if you want to generate a DOM string without React's ID attributes. Use cases include static site generation, or generating HTML/SVG on the client to send to the server for processing.
I also added support for `renderToString` in the browser. The use-case for this method is probably small in client environments, but it's supported in ReactJS, so thought we should support it here too.

Add support for renderToStaticMarkup

---

.gitignore
lib/react.dart

This adds the missing SVG `clipPath` element.
I also added a `.pub/` to the .gitignore. Seems this file is created when running `pub get`, and probably shouldn't be committed to source control.

Add SVG clipPath element

---

lib/react_client.dart

`React.render` in JS returns the rendered component, but react_client doesn't pass along the wrapped result.

Pass along the component instance returned by React.render(...)

---

lib/react_client.dart
lib/react_test_utils.dart
pubspec.yaml
test/child_key_warning_test.dart
test/child_key_warning_test.html

_This PR is a refactor of changes in https://github.com/cleandart/react-dart/pull/58_
react-dart erroneously displays the following console warning at all times because it forces all children to be specified in a Dart list / JS array:
```
Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
```
* Make ReactComponentFactoryProxy an abstract superclass, with implementations ReactDomComponentFactoryProxy and ReactDartComponentFactoryProxy. (This API consistency is useful in react_test_util and external react-dart-related tools.)
* Remove unnecessary `new JsArray.from()` conversion for DOM components.
* Implement variadic support for the DOM/Dart component factories via noSuchMethod, in which children may be …

Permit variadic children (no array necessary) - refactor

---

lib/react_test_utils.dart
test/react_test_utils_test.dart

ReactTestUtils JS Simulate.* and SimulateNative.* supports simulating events on [either React component instances or DOM nodes corresponding to component instances](https://github.com/facebook/react/blob/cd15dc60b8551d72107f068d9e6cebb5c660105d/src/test/ReactTestUtils.js#L430-L442).
The wrappers in react_test_utils.dart, however, type the target of the simulated events to `JsObject`, so it's not possible to pass in an `Element` (DOM node).
* Change parameters on react_test_utils Simulate.* and SimulateNative.* events to `dynamic` so that both `JsObject` component instances and `Element` component DOM nodes can be passed in.
* Update unit tests to verify that the simulated events also work when DOM nodes are passed in.
Run `pub serve`, navigate to …

Change react_test_util.Simulate method parameters to accept DOM nodes

---

lib/react_client.dart

As part of the variadic children changes, Iterables are no longer automatically proxied when passed to React JS. This fixes that.

Convert Iterable children to Lists so that React JS recognizes them

---

lib/react_client.dart

Previously, if a `null` event callback prop was passed into a DOM component, it would throw an error when that event is fired.
Now, `null` callbacks are skipped, preventing the issue.
@hleumas

Add null-check for DOM event handler props

---

lib/react_client.dart

In dart2js-transpiled code, automatic List conversion of React children causes `react-id` attributes to contain lots of extraneous `.$o:0:0:$_jsObject:` parts, and bogs down rendering performance.
This PR eliminates that automatic conversion by always passing in `JsArray`, and resolves this issue.
@hleumas @todbachman-wf @trentgrover-wf @maxwellpeterson-wf

Convert children to JsArrays to work around react-id issue in dart2js

---

pubspec.yaml

- The quiver dependency is outdated and the current range is restrictive (`>=0.18.2 <0.19.0`)
- The only use of quiver is in `react_server.dart` for the `enumerate()` function: 
- https://github.com/cleandart/react-dart/blob/ca6ec7213e185735adc4c50ebeab3fe1a23c3de2/lib/react_server.dart#L9
- https://github.com/cleandart/react-dart/blob/ca6ec7213e185735adc4c50ebeab3fe1a23c3de2/lib/react_server.dart#L142
- The `enumerate()` function has not had any breaking changes since 0.18, and the latest version should still work
Extend the quiver version range to include the latest.
---
@hleumas @trentgrover-wf @greglittlefield-wf 
fyi: @georgelesica-wf

Upgrade quiver dependency

---

.gitignore
README.md
lib/react_test_utils.dart
pubspec.yaml
test/react_test_utils_test.dart

ReactTestUtils has a shallow rendering method, `createRenderer`, that is not exposed through the dart port.
Tests fail to run on master as well.
README was missing the version.
Added method to `react_test_utils.dart` with a small wrapper for ease of API access.
Also updated the `unittest` package. It should be replaced since it is deprecated, but I kept it to just an update for this PR.
Added pub version to README.
@hleumas @trentgrover-wf @greglittlefield-wf

ReactTestUtils shallow rendering

---

lib/react.dart
lib/react_client.dart

The `displayName` property isn't implemented by React-Dart. Implementing it would make the React Devtools far more useful.
Add it and add a default implementation for the `Component` class that just returns the runtime type as a string.
@evanweible-wf @greglittlefield-wf @travissanderson-wf

Add displayName getter.

---

example/test/ref_test.dart
lib/react_client.dart

Refs specified as callbacks were called with the `JsObject` instance, not the Dart component.
This behavior is different than that of `Component.ref(...)`, and makes it impossible to use Dart components with callback refs without knowledge of react-dart internals.
When a ref is specified as a callback to a Dart component, wrap it in a callback that calls the original with the Dart component.
* Open `example/test/ref_test.html`
* Verify that the examples for both string and callback refs work as expected.
---
@hleumas @trentgrover-wf @maxwellpeterson-wf @aaronlademann-wf

Callback refs: return the Dart component, not the JsObject instance 

---

lib/react_client.dart

The "onReset" form event was missing, which caused errors when providing a callback prop with the `'onReset'` key:
```
Uncaught Unhandled exception:
Closure call with mismatched arguments: function 'call'
NoSuchMethodError: incorrect number of arguments passed to method named 'call'
Receiver: Closure: (dynamic) => dynamic
Tried calling: call(Instance of 'JsObjectImpl', ".r[1xv2o].3")
Found: call(e)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
```

Add "onReset" form event

---

lib/react_client.dart

When a Dart component is no longer rendered, its callback ref is called with `null`, which caused null errors when passed into `_getComponent`.
A null-check has been added to fix this case.

Add null-check to Dart component callback refs

---

lib/react.dart
lib/react_client.dart

Sometimes it's helpful, especially in testing, to get a reference to the JavaScript React component that backs the Dart component instance.
These changes store a reference to that instance on the Dart component and expose it as a getter for external use.

Expose a reference to jsThis within Dart components

---

README.md
example/test/get_dom_node_test.dart
example/test/react_test_components.dart
lib/react.dart
lib/react_client.dart
lib/react_client/js_interop_helpers.dart
lib/react_client/react_interop.dart
lib/react_client/synthetic_event_interop.dart
lib/react_server.dart
lib/react_test.dart
lib/react_test_utils.dart
lib/src/react_client/synthetic_event_wrappers.dart
lib/src/react_test_utils/simulate_wrappers.dart
pubspec.yaml
test/child_key_warning_test.dart
test/lifecycle_test.dart
test/lifecycle_test.html
test/react_test_utils_test.dart

Dart 1.13 introduced the new [`js` package](https://pub.dartlang.org/packages/js), which provides an alternate Dart-JS interop that is faster than `dart:js` interop.
react-dart currently uses `dart:js` interop, and could benefit from performance improvements in `package:js`.
This PR upgrades react-dart to use `package:js`, and also includes other changes that improve performance and increase parity with React JS.
Performance tests were run on an earlier version of these changes, as well as for the current react-dart and React JS.
Full results available [in this doc](https://docs.google.com/spreadsheets/d/1GB8QZZGlgFNw4gx6AuRA242Ardfei0sDAYRcHv_osLU/edit?usp=sharing
). Includes data for:
* "unit"-style rendering performance: (https://github.com/greglittlefield-wf/react-dart_perf_unit)
* …

New JS interop, performance/lifecycle improvements

---

.analysis_options
example/test/react_test_components.dart
example/test/speed_test.dart
lib/react.dart
lib/react_client.dart
lib/react_server.dart
lib/react_test_utils.dart
test/lifecycle_test.dart
test/react_test_utils_test.dart
test/test_components.dart

This package was not strong mode compliant (see: [here](https://github.com/dart-lang/dev_compiler/blob/master/STRONG_MODE.md) for more explanation).
And it looks like Dart SDK 1.16.0 will include the `dev_complier` so it would be good to get react-dart in compliance sooner rather than later.
- Added `.analysis_options` file (see: [here](https://github.com/dart-lang/sdk/tree/master/pkg/analyzer#configuring-the-analyzer) for more explanation).
- Got rid of strong mode warnings.
- Most fixes were just making explicit conversions rather than implicit.
- Pull this down in Atom or WebStrom there should be only one hint which is the use of getDomNode which is deprecated.
- If not using Atom or WebStrom run `dartanalyzer --strong lib/**.dart`.
N/A
---
FYA: @hleumas @trentgrover-wf
FYI: …

Enable Strong Mode

---

lib/react_test_utils.dart

When enabling Strong mode in https://github.com/cleandart/react-dart/pull/89 a return type was cast as a specific type while it actually has two valid return types.
- Remove explicit cast
- Remove typing of the parameter.
- Verify all tests pass
N/A
---
FYA: @hleumas @trentgrover-wf @greglittlefield-wf

Untype the componentClass param of _isElementOfType.

---

lib/react_client.dart
test/child_key_warning_test.dart

Variadic children passed into Dart component factories were not being validated (via `markChildrenValidated`).
There was also an issue with that caused the accompanying tests to pass when they should have failed.
* Update tests to ensure that React always emits warnings.
* Validate variadic children passed to Dart components
* Verify that child_key_warning_test passes.
* Comment out the added call to `markChildrenValidated` and verify that the test fails.
---
@hleumas @trentgrover-wf @maxwellpeterson-wf @evanweible-wf @jacehensley-wf @leviwith-wf

Validate variadic children passed to Dart components

---

lib/react_client/js_interop_helpers.dart
lib/react_client/react_interop.dart
lib/react_test_utils.dart
lib/src/react_client/synthetic_event_wrappers.dart
lib/src/react_test_utils/simulate_wrappers.dart
test/js_interop_helpers_test/js_function_test.dart
test/react_test_utils_test.dart

Dart 1.16.0 requires that any libraries that use the `@JS` annotation also be annotated with `@JS`.
See: https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#javascript-interop
* Add `@JS` annotation to libraries where required.
* Add `library` directives for some test files that didn't have any.
Verify that all tests/examples load and run properly in Dartium with a Dart SDK of 1.16.0.
None; these changes should be backwards-compatible.
---
@trentgrover-wf @hleumas

Add @JS() annotation to libraries using JS interop to support Dart 1.16

---

example/test/speed_test.dart
lib/react.dart
lib/react_client.dart
test/ReactSetStateTestComponent.js
test/lifecycle_test.dart
test/lifecycle_test.html

ReactJs supports `setState` callbacks as well as a transactional `setState`. 
For more information on what those are see [here](https://facebook.github.io/react/docs/component-api.html#setstate).
- Allow `setState`, `replaceState`, and `redraw` to accept an optional parameter that will be called after `componentDidUpdate` is called.
- Untype the `newState` param in `setState` so that is can accept and function that accepts two params.
- This will be called before `shouldComponentUpdate`.
- Add tests that ensure the ordering of the callbacks and component methods match the JS order.
- Verify all tests pass.
- None expected, all new logic.
--
FYA: @trentgrover-wf @hleumas @greglittlefield-wf @clairesarsam-wf

Support setState Variations

---

example/test/speed_test.dart
lib/react.dart
lib/react_client.dart
test/ReactSetStateTestComponent.js
test/lifecycle_test.dart
test/lifecycle_test.html

We still want the setState callback variations
- This will need to be breaking change release because anyone overriding `setState`, `replaceState`, or `redraw` will have to change the signatures of the overridden methods.
- Re add the logic that was originally added in #100 and then removed in #101.
- Ensure that the changes made here are the same made in #100 
- Same testing suggestions that are in #100 
- None expected
---
FYA: @trentgrover-wf @hleumas @greglittlefield-wf @clairesarsam-wf

Re-add setState callback support

---

pubspec.yaml

Relax dependency range to include latest release of quiver.

Expand quiver dependency range to include new 0.22

---

lib/react.dart
lib/react_client.dart
lib/react_test.dart
lib/src/typedefs.dart
test/child_key_warning_test.dart

In order for [`over_react` to become strong mode compliant](https://github.com/Workiva/over_react/issues/14), a few changes are necessary in the wrapper:
1. In `react.Component`: 
1. Remove public `props` and `state` fields in-favor of private fields with public getters and setters.
1. This is so that `over_react` can add strong typing to `props` and `state` within `UiComponent` / `UiStatefulComponent`, respectively without generating Dart analyzer errors.
2. Type the props / state arguments of lifecycle methods as `Map`
I also cleaned up a few analyzer errors showing in this repo as well.
---
**FYA** @greglittlefield-wf @jacehensley-wf @clairesarsam-wf @trentgrover-wf

Make adjustments necessary to support strong-mode compliance for over_react

---

lib/react_client.dart

In both Internet Explorer 10 and 11, accessing `DataTransfer.dropEffect` throws an exception for some drag event types.
Handle `dropEffect` access failures the same way `effectAllowed` failures are handled.
---
Please review @greglittlefield-wf @jacehensley-wf @aaronlademann-wf

Handle IE DataTransfer.dropEffect access failures gracefully

---

lib/react_server.dart
pubspec.yaml

quiver is <1.0.0 and breaking changes come more frequently, which requires upkeep of the upper version bound in pubspec.yaml.
Only one utility from quiver is used, so there isn't much benefit to keeping it as a dependency.
* Remove quiver dependency
* Replace usage of `enumerate` with equivalent iteration
* Verify that `data-reactid` values of siblings increment as just like they do in master in `react_test_server.dart` output:
```bash
pub run example/test/react_test_server.dart | tidy -imq
```
Examples:
*  `<span data-reactid="foo.bar.0" /> <span data-reactid="foo.bar.1" />` 👍 
*  `<span data-reactid="foo.baz.$0" /> <span data-reactid="foo.baz.$1" />` 👍

Remove quiver dependency to slim down dependency tree

---

lib/react_client.dart

From https://facebook.github.io/react/docs/events.html#supported-events
> To register an event handler for the capture phase, append Capture to the event name; for example, instead of using onClick, you would use onClickCapture to handle the click event in the capture phase.
Added support for this by adding -`Capture` keys to the event handling logic.
Diff best viewed ignoring whitespace: https://github.com/cleandart/react-dart/pull/114/files?w=1

Add support for capturing event handlers

---

lib/react.dart

Just a doc comment improvement to better align with the React JS docs about the `setState` method.
@greglittlefield-wf @jacehensley-wf @clairesarsam-wf @aaronkavlie-wf @joelleibow-wf

Make it clear that setState merges maps

---

lib/react_client.dart

That `ReactDartComponentInternal ` instance from the first render *should* be GC'd in subsequent renders as it's replaced with a new instance.
However, this wasn't happening since it was retained by the `Component._jsRedraw` closure, which hangs around for the lifetime of the component.
This resulted in the props from the initial render of any given component being retained until the component unmounts.
Big thanks to @bencampbell-wf for discovering the presence of a memory leak and creating a reduced test case!
- Don't reference `internal` inside that closure
Verify via the attached test case that this memory leak has been fixed: [leak_test_case.zip](https://github.com/cleandart/react-dart/files/877003/leak_test_case.zip)

Fix memory leak caused by retained `internal` from first render

---

lib/react_client/js_interop_helpers.dart

Fix for strong mode warning in js_interop_helpers.
Testing: pull down and verify there are no strong mode warnings.

Fix strong mode warning

---

lib/react.dart
lib/react_client.dart

A component's previous state values are stored in `_prevState` for use in `componentDidUpdate`.
However, after a state change completes, _prevState hangs around, leaking memory for any previous state values.
Clear out `_prevState` after it's no longer needed.
- Verify unit tests in CI pass.
- Verify via memory profiling that prevState is no longer leaked:
- Load a page that renders [this OverReact component](https://gist.github.com/greglittlefield-wf/b6ceed11007f8db708a7eabddf8edb39) in dart2js
- Perform a Heap Snapshot in Chrome
- Search for `TestRetainedClass` and verify that no instances show up in the heap, meaning that the values of `prevState` were properly GC'd
Component lifecycle (covered by tests)

Clear out prevState once componentDidUpdate and callbacks complete

---

lib/react_client.dart
lib/src/ddc_emulated_function_name_bug.dart
test/factory/common_factory_tests.dart
test/lifecycle_test.dart

Several dozen tests failed when the test code was compiled using `dartdevc`.
* Resolve failures
* Only a few changes ended up needing to be made.
* [Patch the name property on emulated functions bug to fix the behavior of the `name`/`type` fields](https://github.com/cleandart/react-dart/pull/122/files#diff-12ac054bb8b76f35c1035afef1d94396R361)
* [Two tests cannot be run on ddc currently due to the `noSuchMethod` on emulated functions bug](https://github.com/cleandart/react-dart/pull/122/files#diff-7a382a75d4df367a3f5df34d837d9227R1)
* [Resolve runtime type casting errors](https://github.com/cleandart/react-dart/pull/122/files#diff-c00a02aa016b25a86fb30a2093f935a1L430)
1. All tests should pass when run normally:
```sh
pub run test -p content-shell,chrome
```
Note: I had to do this on …

UIP-2414: Resolve ddc test failures

---

lib/react_client.dart
test/lifecycle_test.dart

Unmounted component instances were retained by the original `ReactElement`'s props via the `ReactDartComponentInternal` object, which is used to tie the Dart component instance to the JS component instance.
This leak is only known to happens in cases where the same ReactElement is held onto, and conditionally rendered. (example: a tabbable area component that conditionally renders its children). Another example is shown in the testing branch listed below:
Null-out references to the component that are no longer needed:
* when the component unmounts
* when the component updates and starts using a new `ReactDartComponentInternal` instance
Store Dart component on the JS component instance instead of the props, to ensure that the memory lifecycles of the Dart and JS components are in-sync, and …

Don't leak internal.component during unmount or rerender

---

lib/react_client.dart
pubspec.yaml
test/lifecycle_test.dart

#123 broke lifecycle methods where `internal.component` was null when being referenced. _(See #124 for more context)_
Revert.
---
__FYA:__ @jacehensley-wf @greglittlefield-wf @clairesarsam-wf 
__FYI:__ @johncblandii @bencampbell-wf @trentgrover-wf

Revert accidental breaking change / (HOTFIX - IMMEDIATE RELEASE)

---

lib/react_client.dart

This PR contains information around a memory leak audit of react-dart, as well as some changes made to reduce the risk of memory leaks.
Reviewed at-risk areas noted in ticket:
- Event handlers
- Transactional `setState` and `setState` callbacks
- Callback `ref`s
- component lifecycle - `shouldComponentUpdate` usage
- component lifecycle - proxying handler closures
Reviewed all other areas of prod code, including:
- component factory proxies and variadic children
- JS bindings
- `SyntheticEvent`s
Performed tests on [internal_instance_refactor](https://github.com/cleandart/react-dart/tree/internal_instance_refactor) branch (UIP-2492 fix, follow-up to https://github.com/cleandart/react-dart/pull/125), with no memory leaks found:
- Retention of component instances by ReactElements (original …

Memory leak audit

---

lib/react_client/react_interop.dart

These fields, soon to be removed in https://github.com/cleandart/react-dart/pull/127, shouldn't be used by most consumers, but it's good to have a deprecation notice anyways.

Deprecate soon to be removed (react 4.0.0) ReactDartComponentInternal fields

---

lib/react_client.dart
pubspec.yaml
test/factory/common_factory_tests.dart
test/react_client_test.dart
test/react_test_utils_test.dart
test/util.dart

When event handlers are added to DOM components, those handlers are converted to functions that proxy the JS events to the Dart event handlers.
Those converted functions are what end up on the `ReactElement` props so that they work when passed to the JS side of React.
However, this causes problems when chaining event handlers that exist on DOM `ReactElement`s, since you need to chain the original Dart function and not the converted JS function.
Allow retrieving the original function from converted event handlers via a helper function backed by an Expando.
Verify that tests pass in:
- the Dart VM: `pub run test -p content-shell`
- dart2js: `pub run test -p chrome`
- ddc: 
- In one terminal: `pub serve test --web-compiler=dartdevc`
- In another: `pub run test -p chrome --pub-serve=8080 -x …

Release 3.6.0: Allow retrieving the original converted event handlers

---

example/test/false_and_null_test.dart
example/test/false_and_null_test.html
js_src/dart_helpers.js
lib/react.js
lib/react_prod.js
lib/react_with_addons.js
lib/react_with_react_dom_prod.js

See <https://github.com/dart-lang/sdk/issues/27485>
Normalize 'undefined' to 'null' in the js layer of interop.
* Load the new test example (<http://localhost:8080/test/false_and_null_test.html>) in chrome and in dartium. It should execute without throwing exceptions.
---
Please review @greglittlefield-wf @aaronlademann-wf

AF-364: Support null return from render()

---

example/geocodes/geocodes.dart
example/geocodes/geocodes.html
example/test/call_and_nosuchmethod_test.html
example/test/context_test.html
example/test/get_dom_node_test.html
example/test/order_test.html
example/test/react_test.html
example/test/ref_test.html
example/test/speed_test.html
example/test/unmount_test.html
lib/react.dart
lib/react_client.dart
pubspec.yaml

Big changes (see commits for full list)
1. Pull this branch
2. Switch to the dart 2 sdk locally, and run `pub get`
1. Run `pub run build_runner test -- -p vm -p chrome`
All tests should pass
3. Switch to Dart 1.24.3, and run `pub get`
1. Run `pub run test -p vm -p content-shell`
All tests should pass.
---
@greglittlefield-wf @robbecker-wf @evanweible-wf @corwinsheahan-wf

React 4.5.0 finishing touches (Dart 2 Compatibility)

---

.travis.yml
CHANGELOG.md
README.md
analysis_options.yaml
dart_test.yaml
example/geocodes/geocodes.dart
example/geocodes/geocodes.html
example/test/call_and_nosuchmethod_test.html
example/test/context_test.html
example/test/get_dom_node_test.html
example/test/order_test.html
example/test/react_test.html
example/test/react_test_components.dart
example/test/ref_test.html
example/test/speed_test.html
example/test/unmount_test.html
lib/react.dart
lib/react_client.dart
lib/react_client/react_interop.dart
lib/src/react_client/dart2_interop_workaround_bindings.dart
pubspec.yaml
test/factory/common_factory_tests.dart
test/react_test_utils_test.dart
test/test_components.dart

1. [x] __PASSED__ [over_react](https://github.com/Workiva/over_react/pull/191)
2. [x] __PASSED__ [wsd](https://github.com/Workiva/web_skin_dart/pull/1083)
* _Had to remove usage of deprecated `isCompositeComponentWithType` test utility to get tests to pass using the `1.24.3` SDK + dartdevc compiler_

Release React 4.5.0 (Dart 2 Compatible!!!)

---

lib/react_client.dart
lib/src/react_client/synthetic_event_wrappers.dart

There's no `SyntheticDataTransfer` object in React JS; synthetic JS mouse events get passed the actual `DataTransfer` object.
Having this JS binding and typing the real `DataTransfer` object as it was causing dart2js errors that looked like:
Warning: 'gJ2' is used reflectively but not in MirrorsUsed. This will break minified code.
14:38:58.512 react_with_react_dom_prod.js:100 Uncaught Error: NoSuchMethodError: method not found: 'gJ2'
Remove the private JS binding, and use the native `DataTransfer` instead.
Trigger a react-dart `onClick` handler and verify it doesn't throw in checked mode.
- `pub serve example/test/`
- In both Dartium (checked mode) and Chrome (dart2js)
- Go to <http://localhost:8080/ref_test.html>
- Click a button
- Verify that the button did something and that there are …

Remove binding for nonexistent SyntheticDataTransfer class

---

lib/react_client.dart
lib/src/react_client/synthetic_event_wrappers.dart

Reverts cleandart/react-dart#151 - it results in some typing errors like so:
```
Unhandled exception:
type 'JSObjectImpl' is not a subtype of type 'DataTransfer' of 'dt' where
JSObjectImpl is from dart:js
DataTransfer is from dart:html
#0      syntheticDataTransferFactory (package:react/react_client.dart:746:65)
#1      syntheticMouseEventFactory (package:react/react_client.dart:784:30)
#2      _convertEventHandlers.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:react/react_client.dart:561:35)
```
This commit had not yet been released, so for the time being (in order to get #153 through) we are going to revert. We can circle back to fix this by finding a way to construct a real DataTransfer object using JS.
@greglittlefield-wf @aaronlademann-wf @kealjones-wk …

Revert "Remove binding for nonexistent SyntheticDataTransfer class"

---

lib/react_client.dart
pubspec.yaml
test/react_client_test.dart

The typing for the unconverted js map for `style` should be `Map<String, dynamic>`.

CPLAT-4447: Type style map as Map<String, dynamic>

---

lib/react_client.dart
pubspec.yaml
test/react_client_test.dart
test/react_test_utils_test.dart

This fixes faulty logic in `testEvent` Tests. Previously the `eventName` supplied to the test was used in `eventData` and would create a false positive because the event name supplied was, in essence, compared to itself, not the actual `eventData`. If the event that was supplied was previously setup to call `onEvent`, would show whatever `eventName` that was provided to the test as `eventData`. Meaning, that the `eventName` comparison would match even if the actual even that fired it was not that event name. This fixes that, using the actual `event.type` as the comparison to the supplied `eventName`.

testEvent logic could create false positives

---

lib/react_client.dart
test/factory/common_factory_tests.dart
test/factory/dart_factory_test.dart
test/factory/dom_factory_test.dart

DOM callback refs weren't working right in dart2js because they weren't being `allowInterop`'d
This bug was introduced as part of cleanup in the JS map PR.
- Revert changes that broke behavior
- Add regression tests for callback refs
- Passing CI

Fix DOM component callback ref regression

---

lib/react.dart
lib/react_client.dart
lib/react_client/react_interop.dart
lib/react_dom_server.dart
lib/react_server.dart
lib/react_test_utils.dart
pubspec.yaml

As part of preparations for ReactJS 16 support coming in version 5.0.0, we need to alert consumers to some important deprecations by annotating those deprecated members, and providing comments about what to use instead _(if applicable)_.
1. [Legacy `context` APIs](https://github.com/cleandart/react-dart/pull/162/commits/f8cd44a63bba1ba8339f0a6a740411e0accc9189)
1. [`isMounted`](https://github.com/cleandart/react-dart/pull/162/commits/33f4f7508801b1549f8a83a7a0a2b40458256451)
1. [`react_test_utils.SimulateNative`](https://github.com/cleandart/react-dart/pull/162/commits/e5398815df1c0567e18db16caae74341df265758)
1. [String `Component.ref`s](https://github.com/cleandart/react-dart/pull/162/commits/911df628b492e61ebb30b6cda94ab351fb791728)
1. …

CPLAT-4335 Add deprecations in preparation for 5.0.0

---

lib/react.dart
lib/react_client.dart
lib/src/react_client/js_backed_map.dart
lib/src/typedefs.dart
test/lifecycle_test.dart
test/lifecycle_test/component2.dart
test/lifecycle_test/util.dart

> ~~__NOT A CLEAN DIFF.__  Will not be a clean diff until #162 / #164 are merged.~~
In ReactJS 16, calling `setState` with a null value no longer triggers an update. However, our interop layer results in an update happening regardless because we always pass an empty `Map` into the JS layer.
https://github.com/cleandart/react-dart/commit/d382d716c2ab3c50a6b558e8887b2301076e72b4
* Update logic within `Component`, and within `JsComponent2Adapter` so that a `null` value passed as the first argument of `setState` does not result in a component update.
* Add tests
---
In `Component`, the first argument of `setState` is `dynamic` so that either a `Map`, or a `TransactionalSetStateCallback` can be provided. Dynamic is gross.
https://github.com/cleandart/react-dart/commit/cbee295abd35357e6539cef7c4 …

CPLAT-4764 React16 setState updates

---

lib/react_client.dart

JsBackedMap needed to be exposed and accessible via `react_client.dart`.
Add `export 'package:react/src/react_client/js_backed_map.dart' show JsBackedMap, JsMap, jsBackingMapOrJsCopy;` to `react_client.dart`.
- CI Passes
None.

Expose JsBackedMap from react_client

---

.travis.yml
lib/react_client.dart
pubspec.yaml

When deprecating a bunch of JS Object stuff in `4.7.0` we missed `emptyJsMap`.
@greglittlefield-wf

Deprecate emptyJsMap

---

lib/react_test_utils.dart
test/react_test_utils_test.dart

`allowInterop` was not being called on functions within `eventData`, resulting in errors like:
```
NoSuchMethodError: method not found: 'preventDefault' (receiver.preventDefault is not a function)
ui_form_components_4_test.dart.browser_test.dart.js 32010:23   JavaScriptObject.preventDefault$0
ui_form_components_4_test.dart.browser_test.dart.js 3703:43    Object.preventDefault$0$x
ui_form_components_4_test.dart.browser_test.dart.js 58867:16   syntheticMouseEventFactory_closure.call$0
ui_form_components_4_test.dart.browser_test.dart.js 86615:32   _$TextInputComponent.handleCancelConfirmToolbarMouseDown$1
ui_form_components_4_test.dart.browser_test.dart.js 1530:14    Object.eval
ui_form_components_4_test.dart.browser_test.dart.js 58781:18   _convertEventHandlers___closure.call$0 …
```

Fix eventdata

---

lib/react.dart
lib/react_client.dart
test/lifecycle_test.dart
test/lifecycle_test/component2.dart
test/lifecycle_test/util.dart

over_react did not have an ideal API to initialize component state within the `init` lifecycle method. A pure over_react solution would have been detrimental to performance. The better solution was to create a direct method in react-dart that can convert a `Map` to a `JsBackedMap` and update the JS layer directly.
- Add the `initializeState` method to `Component2`
- Add an `initializeState` method in `Component2Adapter` and override it in `JsCompoent2Adapter`
- Add Tests
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._
Please review: 
@aaronlademann-wf @greglittlefield-wf @kealjones-wk

CPLAT-5908 Add initializeState to Component2

---

.travis.yml
pubspec.yaml

- Upgrade to build_web_compilers 2.x - no source/test changes were needed, it works as-is.
- Update Travis CI config to also run on dart2 dev channel

Upgrade to build_web_compilers 2.x

---

lib/react.dart
test/lifecycle_test.dart

Calling `setState` in React 15 essentially always causes an update (regardless of whether or not a new state is passed in). This behavior changes in React 16. We want to ensure that `Component` does not break expectations while changing behavior in `Component2`.
- Remove null check that stops the update if `null` is passed in
- Add tests to show that `Component` will update if `null` is passed but `Component2` will not
@aaronlademann-wf @kealjones-wk @greglittlefield-wf @sydneyjodon-wk

CPLAT-6232 normalize set state call

---

example/test/ref_test.dart
lib/react.dart
lib/react_client.dart
lib/react_client/react_interop.dart
test/factory/common_factory_tests.dart

Expose React 16 `createRef` and `forwardRef`.
- Expose React `createRef` function in react_interop.dart and wrap it in a class to handle typing.
- Wrap React `forwardRef` with `ReactJsComponentFactoryProxy`.
Please review:
@kealjones-wk @aaronlademann-wf @greglittlefield-wf @joebingham-wk

CPLAT 4337 Expose React 16 createRef / forwardRef

---

lib/react_client.dart
test/factory/dart_factory_test.dart

Callback refs with non-dynamic arguments weren't being handled properly, and would result in obtuse error messages.
Example: 
- dynamic ref argument (works):
```dart
Foo({'ref': (ref) => _fooRef = ref})
```
- non-dynamic ref argument (does not work):
```dart
Foo({'ref': (FooComponent ref) => _fooRef = ref})
```
In DDC, the ref function would be called correctly, but the ref argument would be of type `NativeJavaScriptObject` instead of the expected component class.
This is because the JS component was being passed instead of the Dart one.
In dart2js, React would throw upon creation of the ReactElement, with the following error.
> Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's …

Fix callback refs with non-dynamic args failing in Dart 2

---

lib/react.dart
lib/react_client/react_interop.dart

- `React.version` was added in 5.0.0, and we want to avoid adding APIs to make it easier to maintain compatibility with both 4.x/5.x
- `Component.bind` was listed as being deprecated in 6.0.0, but we actually want to remove it in 5.0.0 to realize the perf gains of eliminating `_convertBoundValues` from ReactElement creation
- Backport `React.version` from 5.0.0-wip
- Move up removal version for `Component.bind` from 6.0.0 to 5.0.0
n/a

CPLAT-6459 4.x updates in preparation for 5.0.0 release

---

lib/react.dart

It's dynamic in master/5.0.0-wip, and should remain that way to avoid issues in subclasses that implicitly inherit argument types
https://github.com/cleandart/react-dart/blob/master@{29-07-2019}/lib/react.dart#L320
https://github.com/cleandart/react-dart/blob/5.0.0-wip@{29-07-2019}/lib/react.dart#L317

Revert typing change of componentWillReceivePropsWithContext

---

lib/react.dart
lib/react_client.dart
lib/react_test_utils.dart
lib/src/react_client/event_prop_key_to_event_factory.dart
lib/src/react_client/synthetic_event_wrappers.dart
lib/src/react_test_utils/simulate_wrappers.dart
test/react_test_utils_test.dart
test/test_components.dart

React JS added support for `TransitionEvent` and `AnimationEvent` in version 15 via https://github.com/facebook/react/pull/6005, but we have no bindings for them here.
This PR adds bindings and test utils for `SyntheticTransitionEvent` and `SyntheticAnimationEvent`.
@greglittlefield-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk

Add bindings for transition / animation events

---

lib/react.dart

The deprecated lifecycle links within `React.dart` were old or inconsistent. This PR updates them to point to the latest URL.
- Change the react.org link for `componentWillMount` and `componentWillUpdate`
- Add the link for `componentWillReceiveProps`
Please review @kealjones-wk @greglittlefield-wf @aaronlademann-wf @sydneyjodon-wk

Update React.dart Component Lifecycle Links

---

lib/react.dart
test/lifecycle_test.dart

With `implicit_casts: false` in consumer repos, all components exhibit the following error:
> error: The return type of getter 'Component.context' is 'dynamic' which isn't assignable to the type 'Map<dynamic, dynamic>' of its setter 'Component.context'.
Update setter to be dynamic.
- CI passes
- Verify that the issue does not reproduce when pulled into a consumer repo with `implicit_casts: false`
```
dependency_overrides:
react:
git:
url: git@github.com:cleandart/react-dart.git
ref: greglittlefield-wf-patch-1
```

Fix context setter typing to match getter and not fail implicit_casts

---

lib/react_test.dart

react_test.dart hasn't been maintained for a while, and isn't tested. 
We don't plan on supporting it in the future, so it's being deprecated.

Deprecate react_test.dart

---

lib/react.dart
lib/react_client.dart
lib/react_client/bridge.dart
lib/react_client/js_backed_map.dart
test/lifecycle_test.dart
test/react_client/bridge_test.dart
test/react_client/bridge_test.html
test/react_client/js_backed_map_test.dart
test/react_component_test.dart
test/util.dart

There were missing tests for some of the new Component2 code.
- Add full test coverage for `JsBackedMap` methods
- Fix hashCode in DDC
- Add missing test coverage for `setStateWithUpdater` arguments
- Add tests for Component2Bridge
- Add tests for throwing `UnsupportedError`, fix missing `throws` keywords
Boyscouting:
- Make `bridgeForComponent` protected.
- Ensure CI passes

Fill in coverage gaps for Component2

---

lib/react_client.dart
test/react_client_test.dart

`unconvertJsProps` will take in a Dart `Component`, when it shouldn't. This PR adds a check and throws if that happens.
- Add an if statement checking for `Component` only props, and throw if they're found.

CPLAT-7369 Add Check for Dart Map

---

example/test/ref_test.dart
lib/react.dart
lib/react_client.dart
lib/react_client/react_interop.dart
test/factory/common_factory_tests.dart
test/factory/dart_factory_test.dart
test/factory/js_factory_test.dart
test/util.dart

There were some missing areas of test coverage for some of the new APIs added in 5.x, as well as some issues discovered while improving test coverage in the corresponding React 16 branches of over_react.
- Move export of `createRef`/`forwardRef` to `react.dart` instead of `react_client.dart` to avoid conflicting with over_react's exports of similarly-named functions. This change makes them consistent with other react-dart APIs replaced by over_react (findDomNode, Component, etc.)
- Add missing test coverage for refs for JS components, fix conversion of Dart `Ref` objects
- Fix `forwardRef` passing through a `JsRef` instead of a `Ref` to the consumer-provided function
- Add `ReactDartComponentVersion` w/ constants and helpers around `ReactClass.dartComponentVersion`
- `Ref` class …

CPLAT-7459 Test coverage improvements and miscellaneous fixes

---

example/test/react_test_components.dart
lib/react.dart
lib/react_client.dart

`Component.bind` was slated for removal in 5.0.0, and got removed in 5.1.0-wip, but not 5.0.0-wip. We need to remove it.
Note that  the deprecation in master is "5.0.0", while 5.0.0-wip has the out-of-date "6.0.0":
https://github.com/cleandart/react-dart/blob/master/lib/react.dart#L125-L126

Remove Component.bind

---

.travis.yml
example/geocodes/geocodes.dart
pubspec.yaml

The decision has been made to not remove Dart 1 support until the `5.1.0` release that will follow the `5.0.0` release.
@greglittlefield-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk

Restore Dart 1 support

---

lib/react.dart

`TypedSnapshot uses` the on keyword to enforce that the mixin is only used with children of `Component2`. However, because `PropTypes` is implemented in `UiComponent2`, `TypedSnapshot` does not mix with `UiComponent2` well. This is related to https://github.com/dart-lang/sdk/issues/38098.
- Remove the `on` keyword, and ultimately the dependency upon using the mixin with `Component2` based classes.
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk

CPLAT-7571 Remove on Keyword

---

CHANGELOG.md
README.md
pubspec.yaml

This __alpha__ release bumps the ReactJS version to 16.10.1 (#216)

Release react 5.0.0-alpha.1

---

lib/react_client.dart
lib/src/react_client/synthetic_event_wrappers.dart

Work around issue in #154 that necessitated revert of #151

Fix dataTransfer RTE take 2

---

CHANGELOG.md
example/geocodes/geocodes.dart
example/test/get_dom_node_test.dart
example/test/ref_test.dart
lib/react.dart
lib/react_client.dart
lib/react_client/react_interop.dart
pubspec.yaml
test/factory/common_factory_tests.dart
test/factory/dart_factory_test.dart
test/js_interop_helpers_test/shared_tests.dart
test/lifecycle_test.dart
test/react_client_test.dart

This stable, __major__ release of react includes:
- The underlying `.js` files provided by this package are now ReactJS version `16.10.1`.
- Support for the new / updated lifecycle methods from ReactJS 16 [will be released in version `5.1.0`](https://github.com/cleandart/react-dart/milestone/1).
> [Full list of 5.0.0 Changes](https://github.com/cleandart/react-dart/milestone/2?closed=1) 
🚨 __NOTE: This will be the last release of react that supports the Dart 1 SDK.__   🚨
---
__ReactJS 16 breaking changes__
> Source: https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes
Breakage | Migration path
-- | --
Errors in the render and lifecycle methods now unmount the component tree by default. | To prevent this, add error boundaries to the appropriate places in the UI.This can be …

Release react 5.0.0 (stable)

---

example/test/react_test_components.dart
lib/react.dart
lib/react_client/bridge.dart
lib/src/prop_validator.dart
test/lifecycle_test/component2.dart

The `Component2.propTypes` boilerplate was unnecessarily verbose.
1. Add a class that contains the metadata that was previously provided as separate arguments, and change the `PropValidator` typedef signature to only require two arguments - with the second argument being an instance of the metadata class.
__Before:__
```dart
@override
get propTypes => {
'name': (Map props, propName, componentName, location, propFullName) {
if (props[propName].length > 20) {
return ArgumentError('...');
}
return null;
},
};
```
__After:__
```dart
@override
get propTypes => {
'name': (Map props, info) {
if (props[info.propName].length > 20) {
return ArgumentError('...');
}
return null;
},
};
```
1. Update JS interop to pass through the field values from the `ReactValidatorInfo` fields as individual …

CPLAT-8122 Shorten propTypes boilerplate

---

CHANGELOG.md
lib/react_client.dart
lib/src/react_client/synthetic_event_wrappers.dart
pubspec.yaml

#220 was merged/released into the 4.x line, which was using a separate base branch, and was never merged into master. This resulted in that behavior regressing in 5.0.0.
This release merges those changes back in.

Release 5.0.1

---

CHANGELOG.md
lib/react.dart
pubspec.yaml

This patch release of react improves the documentation for deprecated `Component2` lifecycle methods, with in-depth examples for migrating away from `componentWillReceiveProps` and `componentWillUpdate`.
---
@greglittlefield-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk

Release react 5.1.1

---

example/test/function_component_test.dart
lib/hooks.dart
lib/react_client/react_interop.dart
test/hooks_test.dart

Support useCallback hook in react-dart
- Added `useCallback` function
- Wrote tests.
Please review: @kealjones-wk @aaronlademann-wf @greglittlefield-wf @joebingham-wk

CPLAT-8038 Implement/Expose useCallback Hook

---

lib/react_client.dart
test/lifecycle_test.dart

To make testing easier, we want to expose the componentZone field to allow the active zone to be configured to match that of a test.
- Add `currentComponentZone` and set `_ReactDartInteropStatics2`'s `componentZone` equal to it. 
Please review @greglittlefield-wf @aaronlademann-wf @kealjones-wk @sydneyjodon-wk

CPLAT-8698 Expose the componentZone

---

example/test/function_component_test.dart
lib/hooks.dart
lib/react_client/react_interop.dart
lib/src/context.dart
test/hooks_test.dart

Expose the `useContext` hook so that functional components can tap into it.
- Add `useContext` function
- Add an example
- Add tests
- Verify the example works as expected
Please Review @greglittlefield-wf @kealjones-wk @aaronlademann-wf @sydneyjodon-wk

CPLAT-8036 Add useContext Hook

---

lib/react.dart
lib/react_client/react_interop.dart
test/react_strictmode_test.dart
test/react_strictmode_test.html

In order to move ourselves closer to concurrent mode the `StrictMode` component will help us by alerting devs with console errors about issues that are bad practice, deprecated usages, or will prevent concurrent mode.
StrictMode currently helps with:
- Identifying components with unsafe lifecycles
- Warning about legacy string ref API usage
- Warning about deprecated findDOMNode usage
- Detecting unexpected side effects
- Detecting legacy context API
- Implemented StrictMode Component interop.
- Added test for StrictMode rendering.

CPLAT-9057: Implement StrictMode Component

---

example/test/function_component_test.dart
lib/hooks.dart
lib/react_client/react_interop.dart
test/hooks_test.dart

Support useMemo hook in `react-dart`.
- Added `useMemo` function.
- Wrote tests.
Please review: @greglittlefield-wf @aaronlademann-wf @joebingham-wk

CPLAT-8039 Implement/Expose useMemo Hook

---

example/test/function_component_test.dart
lib/hooks.dart
lib/react_client/react_interop.dart
test/hooks_test.dart

Support useLayoutEffect hook in `react-dart`.
- Added `useLayoutEffect` function.
- Wrote tests.
Please review: @greglittlefield-wf @aaronlademann-wf @joebingham-wk

CPLAT-8042 Implement/Expose useLayoutEffect Hook

---

lib/react.dart
lib/react_client.dart
test/factory/common_factory_tests.dart

I'm resurrecting #249, as I've run into a more concrete use-case for `event.persist()` than the one that prompted #249.
Since component updates are not guaranteed to be synchronous in React 16+, the optional callback for `setState` may be called asynchronously on the JS side of things. This means that doing something like passing a `SyntheticEvent` to a consumer callback within that callback will result in ReactJS spitting out a big ugly warning about the event having been recycled.
__Without persist()__
```dart
void handleClick(SyntheticMouseEvent event) {
setState({}, () {
// Ruh roh Scoobs... this could be recycled when they access it.
props.someConsumerCallbackThatNeedsTheEvent(event);
});
}
```
__With persist()__
```dart
void handleClick(SyntheticMouseEvent event) {
event.persist(); …
```

Proxy event.persist() when wrapping synthetic JS events

---

lib/react_client.dart
test/react_client_test.dart

Recommended review: [Whitespace changes only](https://github.com/cleandart/react-dart/pull/261/files?diff=split&w=1)
Currently, registerComponent calls that throw have their errors swallowed by React if they occur in the call stack of a component render (due to the render triggering lazy evaluation of a top-level factory variable).
This can commonly happen if:
- defaultProps throws
- propTypes throws
- can happen when consumedProps throws
- In `_registerComponent` and `_registerComponent2`, add a try-catch-rethrow that also logs the error, in case it's swallowed by React
- Use print instead of window.console.error so it shows up in test output
- In `_registerComponent2` only: add more specific try-catch-rethrows around defaultProps/propTypes accesses, since that's usually what throws 
- …

CPLAT-10894 Rethrow and print registerComponent/registerComponent2 errors

---

CHANGELOG.md
pubspec.yaml

This release includes:
__New Features__
- #244 Add support for [HTML Composition events](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent)
- #263 Add support for [`SyntheticEvent.persist()`](https://reactjs.org/docs/events.html#event-pooling) 
__Fixes / Updates__
- #261 Stop errors thrown within the call stack of `Component.render()` from being swallowed
- #256 Documentation updates _(thanks @barriehadfield !!!)_
__JS Dependency Updates__
- #255 Bump acorn from `6.4.0` to `6.4.1`
- #260 Bump lodash from `4.17.15` to `4.17.19`

Release react 5.4.0

---

lib/hooks.dart
lib/react_client/component_factory.dart
lib/react_client/react_interop.dart

Factory fields have been updated to be getters so they will be lazy evaluated to avoid this warning showing in the console:
```
Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
```

Update factory fields in component factories to be getters

---

example/test/function_component_test.dart
lib/hooks.dart
lib/react_client/react_interop.dart
test/react_memo_test.dart

Updates the `memo` signature to accept a `ReactDartFunctionComponentFactoryProxy` directly, since only function components can be memoized. 
Also removes the `displayName` property as it is not part of React's `memo`, and should be set by the function component config instead.

Update memo signature

---

lib/react_client/component_factory.dart
lib/react_client/react_interop.dart
test/factory/common_factory_tests.dart
test/factory/dart_factory_test.dart
test/factory/dart_function_factory_test.dart
test/factory/dom_factory_test.dart
test/factory/js_factory_test.dart

- Render logic for function and `forwardRef` components weren't being run in the component zone, which was inconsistent with class-based components.
- Existing children tests that verify children are always `List`s in Dart weren't being run for function and `forwardRef` components
- Add component zone logic and tests to `commonFactoryTests`
- Run `commonFactoryTests` for `forwardRef` components
- Update children tests to run for function and `forwardRef` components
- Tests pass
- Revert changes in https://github.com/cleandart/react-dart/pull/269 and verify that children tests fail

Run function/forwardRef components in component zone, run children tests

---

lib/react.dart
lib/react_client/react_interop.dart
test/factory/dart_function_factory_test.dart

While adding onto the `memo` API in OverReact, it was discovered that consuming `props.children` in the `memo` HOC threw a type error because the children weren't guaranteed to be a List as expected.
- Utilize the `alwaysReturnChildrenAsList` flag on `ReactJsComponentFactoryProxy` to ensure children are always wrapped in a List
- Add tests

Ensure `memo`'s `ReactJsComponentFactoryProxy` always uses List children

---

lib/react_client/js_backed_map.dart

`Object.values` is not supported in MSIE 11. We still have consumers that need to support the browser, so our `JsBackedMap.values` implementation needs to support it.
Currently, if you access the `values` getter ([as we do within `forwardRef`](https://github.com/cleandart/react-dart/blob/5.5.0-wip/lib/react_client/react_interop.dart#L238)), MSIE 11 will choke. This fixes that.
@greglittlefield-wf

Make JsBackedMap.values MSIE 11 compatible

---

lib/hooks.dart
test/hooks_test.dart

I came across this RTE recently that occurs during mount as a result of us accessing `jsRef` on the `Ref` when passing through to the  `React.useImperativeHandle` JS interop layer.
Instead of throwing, these changes make it so that the creation of the imperative handle is simply a no-op unless the `Ref` provided is not null.

useImperativeHandle should not throw if ref is null

---

CHANGELOG.md
pubspec.yaml

The latest version of react includes:
- #275 Add `forwardRef2` / `memo2` to fix _"jsification"_ of Dart props
- Deprecates `forwardRef` / `memo`
- #274 _(Security update)_ Bump serialize-javascript JS dependency to version `3.1.0`

Release react 5.6.0

---

CHANGELOG.md
pubspec.yaml

The latest version of react includes:
- #282 Added `SyntheticEvent` utils that remove the need to use the class constructors as well as assist in type checking event types

Release React 5.7.0

---

lib/src/react_client/event_helpers.dart

A helper method was added in stable that we realized wasn't necessary in the 6.0.0 line. This PR just deprecates that method!

Deprecate Helper Method

---

lib/react.dart
lib/react_client.dart
lib/react_client/component_factory.dart
lib/react_client/react_interop.dart
lib/src/react_client/component_registration.dart
lib/src/react_client/dart_interop_statics.dart
lib/src/react_client/private_utils.dart

In prep for react-dart 6.0.0, we're bumping nearly all deprecations to 7.0.0 to make the transition easy. The only deprecates that remain at 6.0.0 are:
- `setReactConfiguration`
- `setReactDOMConfiguration`
- `ReactDartComponentFactoryProxy.reactComponentFactory` and `ReactDartComponentFactoryProxy2.reactComponentFactory`
- `ReactJsContextComponentFactoryProxy.factory`, `ReactJsComponentFactoryProxy.factory`, and `ReactDomComponentFactoryProxy.factory`
Because they are removed [here](https://github.com/cleandart/react-dart/pull/277) in 6.0.0.
Also, `SyntheticEventTypeHelpers.isFormEvent` because it was removed [here](https://github.com/cleandart/react-dart/pulls?q=is%3Apr+is%3Aclosed) in 6.0.0.

Bump all deprecations to 7.0.0

---

.travis.yml
test/lifecycle_test/util.dart

CI was failing on every commit because the code was formatted under Dart 2.9, and CI was only skipping formatting on `dev` runs and not the Dart 2.10 `stable` run.
Previously, stable runs were broken due to build issues, but now that that's fixed, we can format on stable.
- Format on Dart 2.10.4 (stable)
- Only check formatting on stable runs
- Verify all Travis builds are green

Format on Dart 2.10.4, only check formatting on stable runs

---

CHANGELOG.md
pubspec.yaml

- #289 Update most deprecations that were slated for removal in v6.0.0 to be slated for removal in v7.0.0 instead. To keep the migration to v6.0.0 as easy as possible, only APIs that are known to be completely unused will be removed in v6.0.0. Therefore, most APIs that were marked for removal in v6.0.0 will remain until the v7.0.0 release. This PR updated deprecation annotations to reflect this. 
- #287 Deprecate `SyntheticEvent.isFormEvent`. Because form events do not exist as their own type in ReactJS, this helper will be removed in v6.0.0. Instead, check for the expected [form event types](https://reactjs.org/docs/events.html#form-events).

Release React 5.7.1

---

lib/src/react_client/event_helpers.dart
test/react_client/event_helpers_test.dart

When [we updated the synthetic event system to use duck typing instead of Dart `is` type checking](https://github.com/cleandart/react-dart/pull/288), we created a possible null exception that presents as seen below when the event is null: 
```
Error: Cannot use 'in' operator to search for 'key' in null
```
This is a regression since before we made the switch, a check like this would have simply returned false:
```dart
final someSyntheticEvent = null;
final isSyntheticMouseEvent = someSyntheticEvent is SyntheticMouseEvent; // false
```
but now, it throws the exception when the logic is updated to:
```dart
final someSyntheticEvent = null;
final isSyntheticMouseEvent = someSyntheticEvent.isMouseEvent; // throws RTE
```
1. Add null checks before calling `hasProperty` and `_checkEventType`.
2. …

Add null handling to synthetic event duck type checking

---

.github/workflows/dart_ci.yml
Dockerfile
README.md

Using Github actions for CI is cool, and Travis is dead.

Set up Github actions CI

---

Dockerfile
lib/src/react_client/event_helpers.dart
test/react_test_utils_test.dart
test/test_components.dart
test/test_components2.dart

`isMouseEvent` was incorrectly returning `false` for events created via `Simulate.contextMenu`.
It looks like we were missing type-checking test coverage for contextmenu events (I checked to see if any more were missing, but contextmenu was the only one).
- Update `type` string checks in `isMouseEvent` so that it returns `true` for simulated context menu events
- Update test coverage
- CI passes

Fix isMouseEvent returning false for simulated context menu events

---

lib/react_client/js_backed_map.dart
lib/src/context.dart
lib/src/react_client/private_utils.dart

Dart 2.12 includes changes to `setProperty` that disallow passing in Dart functions, since they are not callable by JS code. https://github.com/dart-lang/sdk/commit/d683f33f5bfefe92ea1a590a800c7e41b213f69c
This breaks passing function props to Dart components, since `JsBackedMap` stores those values using `setProperty` under the hood.
```
Assertion failed: org-dartlang-sdk:///lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart:166:7
_isJsObject(f) ||
!JS<bool>('bool', '# instanceof #.Function', f, global_)
"Dart function requires `allowInterop` to be passed to JavaScript."
dart:sdk_internal                                        setProperty
package:react/react_client/js_backed_map.dart 66:5       _set
dart:sdk_internal                                        addAll …
```

CPLAT-13185 Fix JsBackedMap for Dart 2.12

---

CHANGELOG.md
pubspec.yaml

This patch release includes
#305 Fix JsBackedMap for Dart 2.12

RM-93289 Release react 6.0.1

---

.github/workflows/dart_ci.yml
lib/react_client/component_factory.dart
pubspec.yaml

`generateJsProps` is used in `ReactComponentFactoryProxy` classes to construct `React.createElement`-compatible JS props objects from Dart props Maps, and includes conversion of refs and optional deep jsifiation of nested objects.
`React.createElement` is the primary recipient of these kinds of JS props objects, but there are cases in which consumers may need to pass those props to other JS recipients. 
For example, you may want to call a JS callback with those props, or even opt to perform conversion of props before they get to the `ReactComponentFactoryProxy`.
- Export `generateJsProps` as a public API
- Fix build by pinning meta
N/A (CI passes)

CPLAT-15062 Export generateJsProps

---

CHANGELOG.md
pubspec.yaml

This release includes #319 Add `baseURI` polyfill for IE 11 compatibility on Dart 2.13.

RM-110959 Release react-dart 6.1.1

---

.github/workflows/dart_ci.yml
pubspec.yaml

Summary
---
Client Platform is updating dependencies! Read more details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
This batch is to find and open PRs to upgrade dependency_validator to v2.
Additional manual work that might be needed (CP will do):
[ ] Run dependency_validator to repos that aren't running it,
but do have the dependency. 
[ ] Fix CI due to removing an ignore that was actually needed.
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/update_dep_validator`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/update_dep_validator)

Upgrade dependency_validator

---

CHANGELOG.md
pubspec.yaml

* [Bump elliptic from 6.5.3 to 6.5.4](https://github.com/Workiva/react-dart/pull/308)
* [Update README.md](https://github.com/Workiva/react-dart/pull/309)
* [Bump ssri from 6.0.1 to 6.0.2](https://github.com/Workiva/react-dart/pull/311)
* [Bump lodash from 4.17.20 to 4.17.21](https://github.com/Workiva/react-dart/pull/312)
* [Bump browserslist from 4.16.1 to 4.16.6](https://github.com/Workiva/react-dart/pull/313)
* [Upgrade to Dart 2.13](https://github.com/Workiva/react-dart/pull/315)
* [Bump path-parse from 1.0.6 to 1.0.7](https://github.com/Workiva/react-dart/pull/318)
* [Raise the Dart SDK minimum to at least 2.11.0](https://github.com/Workiva/react-dart/pull/323)
* [Upgrade dependency_validator](https://github.com/Workiva/react-dart/p …

RM-113709 Release react-dart 6.1.3

---

.github/workflows/dart_ci.yml
dart_test.yaml
pubspec.yaml
test/js_builds/shared_tests.dart

In order to get the CI build passing on 2.13.4 and 2.14.x (stable), we need to widen some dependency ranges.
It also appears that https://github.com/dart-lang/sdk/issues/43939 was fixed at some point in the 2.14.x line of release _(thus the new tag used to skip those dupe `console.warn` tests unless we're running the tests in 2.13.x)_.

Fix stable ci build

---

lib/react_client/js_interop_helpers.dart
test/react_client/js_interop_helpers_test.dart
test/react_client/js_interop_helpers_test.html

In dart2js, passing a JS object into `identityHashCode` results in an `$identityHash` property being added to it: https://github.com/dart-lang/sdk/issues/47595.
This is undesirable since this property can get added to nested props maps of JS components.
- Replace usage of `identityHashCode` with `_jsObjectFriendlyIdentityHashCode`, which doesn't call `identityHashCode` for JS objects
- Add regression test
- Add other tests for `jsifyAndAllowInterop`, based on the Dart SDK's `allowInterop` tests
- CI passes
- (If desired) Change `_convertedObjects` back to `Map.identity()` and verify tests fail in dart2js:
```sh
pub run build_runner test -r '--build-filter=test/react_client/js_interop_helpers_test**' -- test/react_client/js_interop_helpers_test.dart
```

Work around $identityHash being added to JS objects passed into jsifyAndAllowInterop

---

CHANGELOG.md
Dockerfile
pubspec.yaml
skynet.yaml

Now that we've moved this package within the Workiva org, we should publish the JS bundles to our CDN so that Workiva customers get assets cached based on the react package version, not the Workiva application version.

RM-138703 Release react-dart 6.1.6 (Publish JS bundles to Workiva CDN)

---

example/README.md
tool/run_consumer_tests.dart

This Sourcegraph batch replaces deprecated commands from the Dart SDK with the new ones.
All new CLI commands now live under the main `dart` executable. See this issue for the details
https://github.com/dart-lang/sdk/issues/46100
This PR might need to be checked or tweaked for possible errors in the arguments to 
`dart analyze` and `dart format` since they take slightly different arguments than the original.
In most cases for analyze all the arguments can be removed and it can just be `dart analyze`.
Some of the argument changes were difficult to match and replace in an automated way. Since
there are only a few places that might break, it'll be easier to let the batch create the PR
and then manually adjust them.
`-w` should be removed automatically since overwriting files is now the …

Replace deprecated commands with new dart commands

---

skynet.yaml

This adds a skynet config that verifies that the github workflow is successful this means that if the tests fail this will cause the release pipeline to fail with the current setup if the github workflow fails the pipeline will continue on like everything is fine when things could be very broken. This is a temporary fix with the hope that pipelines/CID will be able to just check the github workflow run instead of needing this.

FW-151 Add skynet config that verifies that github workflow is successful

---

lib/react_client/js_interop_helpers.dart
test/react_client/js_interop_helpers_test.dart
test/react_client/js_interop_helpers_test.html

Currently, when jsifyAndAllowInterop encounters a non-JsObject frozen object, such as [the frozen `children` array](https://github.com/facebook/react/blob/1ad8d81292415e26ac070dec03ad84c11fbe207d/packages/react/src/ReactElement.js#L413) of a JSX Element, it throws as a result of `identityHashCode` trying to write a property on it (Dart SDK issue: https://github.com/dart-lang/sdk/issues/36354).
This can occur when wrapping JS components in Dart and forwarding props that contain frozen arrays them to another component.
```
Uncaught TypeError: Cannot add property Symbol(_identityHashCode), object is not extensible
at Object.identityHashCode (core_patch.dart:41:42)
at CustomHashMap.new._jsObjectFriendlyIdentityHashCode (js_interop_helpers.dart:16:51)
at CustomHashMap.new.containsKey …
```

FED-358 Work around identityHashCode throwing for non-extensible objects

---

CHANGELOG.md
pubspec.yaml

* [Bump minimist from 1.2.5 to 1.2.6](https://github.com/Workiva/react-dart/pull/335)
* [Bump ansi-regex from 4.1.0 to 4.1.1](https://github.com/Workiva/react-dart/pull/338)
* [Replace deprecated commands with new dart commands](https://github.com/Workiva/react-dart/pull/340)
* [FW-151 Add skynet config that verifies that github workflow is successful](https://github.com/Workiva/react-dart/pull/341)
* [Narrow dependency_validator range to avoid NNBD issue](https://github.com/Workiva/react-dart/pull/342)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/6.1.6...Workiva:release_react-dart_6.1.7
Diff Between Last Tag and New Tag: …

RM-139349 Release react-dart 6.1.7

---

lib/src/react_client/factory_util.dart
test/factory/js_factory_test.dart
test/factory/js_factory_test.js

Some JS components, like `Tab` expect no children to be passed to them.
However, when rendered from Dart, Tab's propTypes warn about children not being supported, even when no children are provided:
```
react.js:6902 Warning: Failed prop type: The prop `children` is not supported. Please remove it.
at Tab (http://localhost:8080/packages/react_material_ui/react-material-ui-development.umd.js:46607:19)
```
This is because, when there are no children, `ReactJsComponentFactoryProxy` passes `null` into createElement, and the `unsupportedProp` validation checks warns when the prop is undefined.
- Return `jsUndefined` instead of `null` from `generateChildren` when the children prop is empty
- Add regression test

FED-202 Return `jsUndefined` instead of `null` when children prop is empty

---

CHANGELOG.md
pubspec.yaml

* [FED-202 Return `jsUndefined` instead of `null` when children prop is empty](https://github.com/Workiva/react-dart/pull/350)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/6.1.7...Workiva:release_react-dart_6.1.8
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/6.1.7...6.1.8
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4743698779471872/?repo_name=Workiva%2Freact-dart&pull_number=351)

RM-156571 Release react-dart 6.1.8

---

CHANGELOG.md
pubspec.yaml

* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/react-dart/pull/354)
* [Pin mockito 5](https://github.com/Workiva/react-dart/pull/355)
* [FED-1161 Unpin mockito, fix CI](https://github.com/Workiva/react-dart/pull/356)
* Minor changes:
* [FED-1254 add Suspense component](https://github.com/Workiva/react-dart/pull/357)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/6.1.8...Workiva:release_react-dart_6.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/6.1.8...6.2.0
This pull …

RM-171359 Release react-dart 6.2.0

---

CHANGELOG.md
lib/hooks.dart
lib/react.dart
lib/react_client.dart
lib/react_client/component_factory.dart
lib/react_client/react_interop.dart
lib/src/react_client/component_registration.dart
lib/src/react_client/dart_interop_statics.dart
lib/src/react_client/event_helpers.dart
lib/src/react_client/factory_util.dart
lib/src/react_client/private_utils.dart
test/hooks_test.dart

react-dart 7.0.0 will contains some breaking changes to APIs that are not yet deprecated in the 6.x line.
The 7.0.0 WIP branch also relies some API additions that aren't present in 6.x, so we'll want to backport them to ensure consumers can transition to these new APIs before setting their lower bounds to 7.0.0.
- Deprecate APIs to be removed in 7.0.0
- Update existing outdated deprecations for APIs that say they'll be removed in 7.0.0, but won't yet be removed
- These were mostly `Component` and its associated APIs, which we don't have a timeline for removing
- Backport APIs `htmlMain` and `useRefInit`
- Add draft changelog entry for 7.0.0.
- I had this written up but not committed anywhere, and figured I'd add it now to help provide context during review of this PR. We can refine this …

FEDX-414 Add APIs and update deprecations in preparation for 7.0.0 release

---

CHANGELOG.md
lib/react_client/react_interop.dart
pubspec.yaml

We need to release the changes merged to master, notably `htmlMain` so that consumers can support both react-dart 6.x and 7.x (once 7.x is released).
While removing APIs in the 7.0.0 WIP branch, I also noticed a few I missed that we should deprecate and remove in 7.0.0.
- Update changelog and version meta for react-dart 6.3.0
- Deprecate ReactElementStore, JsError, markChildValidated
CI passes

RM-215032 Release react-dart 6.3.0

---

CHANGELOG.md
lib/react.dart
lib/react_client.dart
lib/react_client/bridge.dart
lib/react_client/component_factory.dart
lib/react_client/react_interop.dart
lib/src/react_client/component_registration.dart
lib/src/react_client/dart_interop_statics.dart
lib/src/react_client/event_helpers.dart
lib/src/react_client/factory_util.dart
lib/src/react_client/internal_react_interop.dart
lib/src/react_client/private_utils.dart
lib/src/react_client/synthetic_event_wrappers.dart
test/factory/common_factory_tests.dart
test/js_builds/shared_tests.dart
test/react_memo_test.dart

This PR is dependent on https://github.com/Workiva/react-dart/pull/373. I've made this PR into the null safety branch so that this is a clean diff, and we'll want to merge that PR first before this one.
There are some APIs we've planned on removing in 7.0.0, and it's time to remove them. 
Some APIs have already been removed in the v7_wip branch, and this PR should remove the rest of them.
Notably, there were quite a few APIs that aren't being removed outright, but instead are being made private.
- lib/react_client/react_interop.dart
- Remove unused, deprecated APIs
- JsPropValidator
- `ReactElementStore` 
- `React.createFactory`
- Make deprecated APIs private (mostly moved to a new lib/src/react_client/internal_react_interop.dart):
- InteropContextValue
- ReactDartContextInternal
- …

FED-1727 Remove the rest of the deprecated APIs for v7

---

.github/workflows/dart_ci.yml

We're only running GitHub Actions in 2.18, and not 2.19 (the latest minor of Dart 2).
Add 2.19.6 to the GitHub Actions matrix.
CI passes, including new 2.19.6 run.

FED-1850 Add Dart 2.19 to GHA matrix

---

lib/src/react_client/event_helpers.dart
test/mockito.dart
test/mockito.mocks.dart
test/react_client/event_helpers_test.dart

When testing these changes, we ran into a case where a consumer was mocking `type`, and relying on type-checking utilities to respect that.
```dart
class MockSyntheticEvent extends Mock implements SyntheticEvent {}
```
```dart
final mockEvent = MockSyntheticEvent();
when(mockEvent.type).then('click');
print(mockEvent.isMouseEvent);
```
Previously, this would print `true`, but in v7_wip, it prints `false`.
- Update event type checking to match old behavior.
- Add regression test and additional test
- Verify that regression test fails in the commit before the fix was introduced
- CI link: https://github.com/Workiva/react-dart/actions/runs/6817966382/job/18542598172
- Expected failing test: `Synthetic event helpers SyntheticEventTypeHelpers checks types correctly for Mock objects with `type` …

FED-1881 Fix regression in SyntheticEvent mock class type-checking

---

CHANGELOG.md
lib/react_client/react_interop.dart
lib/src/react_client/dart2_interop_workaround_bindings.dart
test/lifecycle_test.dart
test/react_client_test.dart
test/react_dom_test.dart
test/react_dom_test.html
test/react_test_utils_test.dart
test/util.dart

The existing nullability/typings for `ReactDom.findDomNode` and `ReactDom.render` exported from `package:react/react_client/react_interop.dart` are incorrect.
```dart
class ReactDom {
Element findDOMNode(dynamic object) {/*...*/}
ReactComponent render(ReactElement component, Element element) {/*...*/}
/*...*/
}
```
`findDOMNode` returns null in many cases, but its return type is incorrectly non-nullable.
`render` returns null for some cases (function components, `null`), `Element` for DOM components, and `CharacterData` for strings and numbers, but is incorrectly typed as non-nullable `ReactComponent`. The `component` argument also accepts `null` and other "ReactNode" arguments to rendered, but its type is incorrectly non-nullable and restricted to just `ReactElement`.
These bad typings …

FED-1910 Fix react_dom API typings, add tests

---

pubspec.yaml

* Minor changes:
* [FED-2298 Add ReactNode typedef](https://github.com/Workiva/react-dart/pull/384)
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/7.0.1...Workiva:release_react-dart_7.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/7.0.1...7.1.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4743698779471872/?repo_name=Workiva%2Freact-dart&pull_number=385)

RM-226888 Release react-dart 7.1.0

---

lib/src/react_client/event_helpers.dart
test/react_client/event_helpers_test.dart

In Dart SDK versions with null-safety enabled, [the interop](https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/dart2js/html_dart2js.dart#L22421-L22422) for `MouseEvent.dataTransfer` is non-nullable despite the [JS spec for `dataTransfer`](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent/dataTransfer) clearly indicating that it can be null.
This can cause the SDK to throw when a `MouseEvent` is manually constructed _(e.g. [in a test utility](https://github.com/workiva/over_react_test/blob/dd90164b94e18faac363ced0dc0508ca780183b0/lib/src/over_react_test/dom_util.dart#L63-L69))_, and the `dataTransfer` getter is then accessed when running with `sound_null_safety` enabled:
```
Unexpected null value encountered in Dart web platform libraries.
```
> [More info about these …

FED-2812 Catch MouseEvent.dataTransfer null exception

---

pubspec.yaml

* [FEDX-693-take4 : GHA OSS changes](https://github.com/Workiva/react-dart/pull/390)
* [Replace mockito with mocktail](https://github.com/Workiva/react-dart/pull/395)
* [FED-2812 Catch MouseEvent.dataTransfer null exception](https://github.com/Workiva/react-dart/pull/398)
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/7.1.0...Workiva:release_react-dart_7.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/7.1.0...7.1.1
This pull request can be recreated by clicking …

RM-244851 Release react-dart 7.1.1

---

.github/workflows/dart_ci.yml
Dockerfile
example/test/react_test_components.dart
skynet.yaml

We moved to Github Actions but need to fix some things internal to Workiva before being able to remove Dockerfile and skynet.yaml completely. This undoes those removals and drops older versions of Dart from CI.

Add CDN publish back temporarily

---

example/suspense/suspense.dart
lib/react.dart
lib/react_client/react_interop.dart
lib/src/react_client/lazy.dart
test/factory/common_factory_tests.dart
test/react_lazy_test.dart
test/react_lazy_test.html
test/react_suspense_test.dart

Adding in a React.lazy implementation 
This is part one of [FED-3114](https://github.com/Workiva/over_react/pull/941)

FED-3207 Add react lazy

---

CHANGELOG.md
pubspec.yaml

* Minor changes:
* [FED-3207 Add react lazy](https://github.com/Workiva/react-dart/pull/406)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/7.1.3...Workiva:release_react-dart_7.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/7.1.3...7.2.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4743698779471872/?repo_name=Workiva%2Freact-dart&pull_number=408)

RM-270006 Release react-dart 7.2.0

---

.github/workflows/dart_ci.yml
dart_test.yaml
pubspec.yaml
tool/delete_dart_2_only_files.sh

Related over_react PR: https://github.com/Workiva/over_react/pull/958
We should support Dart 3.
react-dart can currently be consumed in Dart 3, despite not supporting it in its SDK constraints, due to the way [Dart 3 treats null-safe packages as compatible](https://dart.dev/resources/dart-3-migration#dart-3-backwards-compatibility). 
However, we don't officially support Dart 3, and our automated CI checks don't validate that it works properly in Dart 3.
Also, we still need to support Dart 2 for the time being, so ideally we'd be able to support both Dart 2 and 3 in the same react-dart version, and run CI against each Dart version.
- Raise SDK constraints to explicitly support Dart 3
- Update CI to run against both Dart 2 and Dart 3
- In Dart 3 runs, delete non-null-safe browser test …

FED-3253 Officially support Dart 3

---

CHANGELOG.md
README.md
pubspec.yaml

* Minor changes:
* [FED-3283: React 18 js files](https://github.com/Workiva/react-dart/pull/414)
* [FED-3253 Officially support Dart 3](https://github.com/Workiva/react-dart/pull/409)
* [Raise the build_web_compilers dependency max to v5.0.0](https://github.com/Workiva/react-dart/pull/410)
* [Raise the meta dependency min to v1.16.0](https://github.com/Workiva/react-dart/pull/411)
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/7.2.0...Workiva:release_react-dart_7.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/7.2.0...7.3.0
The logs for the request that created this PR can be found …

RM-288881 Release react-dart 7.3.0

---

CHANGELOG.md
pubspec.yaml

* [FED-3927 Fix failing test on Dart 3](https://github.com/Workiva/react-dart/pull/420)
* [no_entrypoint_imports](https://github.com/Workiva/react-dart/pull/421)
* [FED-4060 Set up gha-dart-oss](https://github.com/Workiva/react-dart/pull/422)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/react-dart/compare/7.3.0...Workiva:release_react-dart_7.3.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/react-dart/compare/7.3.0...7.3.1
This pull request can be recreated by clicking …

RM-327375 Release react-dart 7.3.1
